---
title: "데이터 전처리 (Preprocessing)"
description: "기계학습과 시각화를 위한 다양한 데이터 정제(Cleansing)하는 방법을 다룹니다."
date: today # 날짜 설정: now, last-modified
author:
  - name: 이광춘
    affiliation: TCS
title-block-banner: false
format:
  html:
    theme: 
      - flatly
      - css/quarto-fonts.css
    code-fold: false
    code-overflow: scroll
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github    
    self-contained: false
editor_options: 
  chunk_output_type: console
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true  
---


```{r}
#| include: false
library(dplyr)
library(palmerpenguins)
```


# 결측값 제거

[참고자료: [결측데이터](https://aispiration.com/data-science/ds-missing.html)]{.aside}

:::{layout-ncol="2"}

```{r}
#| eval: false

library(tidyverse)
library(palmerpenguins)

penguins
```

```{r}
#| echo: false

library(tidyverse)
library(palmerpenguins)

penguins

```
:::

## 행기준 제거

:::{layout-ncol="2"}

```{r}
#| eval: false

library(tidyverse)
library(palmerpenguins)

penguins %>% 
  drop_na()
```

```{r}
#| echo: false

library(tidyverse)
library(palmerpenguins)

penguins %>% 
  drop_na()

```

:::


## 열기준 제거

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  select_if(~ !any(is.na(.)))
```

```{r}
#| echo: false

penguins %>% 
  select_if(~ !any(is.na(.)))
```

:::


## 결측값 현황

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  summarise(across(everything(), ~ sum(complete.cases(.)))) %>% 
  pivot_longer( cols = everything(), names_to = "변수", values_to = "정상값") %>% 
  mutate(결측비율 = 1 - 정상값 / nrow(penguins))
```

```{r}
#| echo: false

penguins %>% 
  summarise(across(everything(), ~ sum(complete.cases(.)))) %>% 
  pivot_longer( cols = everything(), names_to = "변수", values_to = "정상값") %>% 
  mutate(결측비율 = 1 - 정상값 / nrow(penguins))
```

:::


# 중복 제거

## 행기준 제거

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins_dup <- penguins %>% 
  slice(1:5) %>% 
  bind_rows(penguins %>% slice(1:5))

penguins_dup

penguins_dup %>% 
  distinct()
```

```{r}
#| echo: false

penguins_dup <- penguins %>% 
  slice(1:5) %>% 
  bind_rows(penguins %>% slice(1:5))

penguins_dup

penguins_dup %>% 
  distinct()
```
:::


## 열기준 제거

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins_cols <- penguins %>% 
  select(1:3) %>% 
  cbind(penguins %>% select(1:3)) 

penguins_cols

duplicated_colnames <- duplicated(colnames(penguins_cols))

penguins_cols[!duplicated_colnames] %>% 
  as_tibble()
```

```{r}
#| echo: false

penguins_cols <- penguins %>% 
  select(1:3) %>% 
  cbind(penguins %>% select(1:3)) 

# penguins_cols

duplicated_colnames <- duplicated(colnames(penguins_cols))

penguins_cols[!duplicated_colnames] %>% 
  as_tibble()
```
:::


# 자료형 변환

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  select(species, year, island, bill_length_mm) %>% 
  mutate(year = lubridate::make_date(year = year, month = 7L, day = 1L))
```

```{r}
#| echo: false

penguins %>% 
  select(species, year, island, bill_length_mm) %>% 
  mutate(year = lubridate::make_date(year = year, month = 7L, day = 1L))

```

:::


# 이상점 제거


:::{layout-ncol="2"}

```{r}
#| eval: false

penguin_stat <- penguins %>% 
  drop_na() %>% 
  summarise(mean = mean(bill_length_mm),
            sd   = sd(bill_length_mm)) 

penguins %>% 
  filter(bill_length_mm < penguin_stat$mean - 2 * penguin_stat$sd |
         bill_length_mm > penguin_stat$mean + 2 * penguin_stat$sd)
```

```{r}
#| echo: false

penguin_stat <- penguins %>% 
  drop_na() %>% 
  summarise(mean = mean(bill_length_mm),
            sd   = sd(bill_length_mm)) 

penguins %>% 
  filter(bill_length_mm < penguin_stat$mean - 2 * penguin_stat$sd |
         bill_length_mm > penguin_stat$mean + 2 * penguin_stat$sd)

```

:::

# 공백문자제거

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  mutate(species = str_trim(species))
```

```{r}
#| echo: false

penguins %>% 
  mutate(species = str_trim(species))

```

:::


# 칼럼 변환

:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  mutate_if(is.factor, toupper)
# mutate_if(is.factor, toupper)
```

```{r}
#| echo: false

penguins %>% 
  mutate_if(is.factor, toupper)
  # mutate_if(is.factor, toupper)
```

:::


# 특정문자 치환


:::{layout-ncol="2"}

```{r}
#| eval: false

penguins %>% 
  mutate_if(is.factor, toupper)
```

```{r}
#| echo: false

penguins 
  
  
```

:::


