project:
  type: website
  output-dir: docs

website:
  title: "데이터 과학"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: cmdline.qmd
        text: "콘솔 데이터 분석"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



