project:
  type: website
  output-dir: docs
  preview:
    port: 3333
    browser: true

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "데이터 과학"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#0068B7"  
    left:
      - href: index.qmd
        text: "Home"
      - text: "개발환경"
        menu:
        - href: 00_setup.qmd
          text: "실습환경"
        - href: 01_setup_scenario.qmd
          text: "환경설정상세"
      - text: "교재"
        menu:
        - href: 10_cmdline.qmd
          text: "콘솔 데이터 분석"
        - href: 11_shell.qmd
          text: "쉘(Shell)"
        - text: "-----"
        - text: "프로그래밍: R"        
          
format:
  html:
    theme: cosmo
      - litera
      - css/quarto-fonts.css
    toc: true

execute:
  freeze: true

