project:
  type: website
  output-dir: docs
  preview:
    port: 3333
    browser: true
  render:
    - "*.qmd"
    - "!flexdashboard/"
    - "!*.ipynb"
    - "!learnr/"
    - "!flipbook"

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "데이터 과학"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#0068B7"  
    left:
      - href: index.qmd
        text: "들어가며"
      - text: "커리큐럼"
        menu:
          - href: curriculum_2023.qmd
            text: "2023년"
          - href: curriculum_2022.qmd
            text: "2022년"
      - text: "모래시계"
        menu:
          - href: timer_five.qmd
            text: "5 분"
          - href: timer_ten.qmd
            text: "10분"
          - href: timer_twenty.qmd
            text: "20분"
          - href: timer_thirty.qmd
            text: "30분"            
          - href: timer_hour.qmd
            text: "1시간"                        
      - text: "개발환경"
        menu:
          - href: 00_setup.qmd
            text: "실습환경"
          - href: 01_setup_bash.qmd
            text: "CLI 개발환경"
          - href: 02_setup_sql.qmd
            text: "Sqlite 데이터베이스"
          - href: 03_setup_python.qmd
            text: "파이썬"
          - href: hello_world_jupyter.qmd
            text: "쥬피터 노트북"
          - href: 04_setup_r.qmd
            text: "고급 데이터과학: R"            
      - text: "교재"
        menu:
          - text: "-----"
          - href: 99_statistics.qmd
            text: "통계학"
          - text: "-----"
          - href: 10_cmdline.qmd
            text: "명령라인 데이터 분석"
          - href: 11_shell.qmd
            text: "쉘(Shell)"
          - href: 12_writing.qmd
            text: "디지털 글쓰기(보고서)"
          - href: 13_git.qmd
            text: "Git/GitHub"
          - text: "-----"
          - href: 20_sql.qmd          
            text: "프로그래밍: SQL"
          - href: 21_r.qmd          
            text: "프로그래밍: R"
          - href: 22_python.qmd          
            text: "프로그래밍: 파이썬"          
          - text: "-----"
          - href: 30_dashboard.qmd
            text: "대쉬보드"
          - href: 31_models.qmd          
            text: "기계학습"
          - href: 32_product.qmd          
            text: "데이터과학 제품과 서비스"            
          - text: "-----"
          - href: 41_time_series.qmd
            text: "시계열 데이터"
          - href: 42_network.qmd
            text: "네트워크 데이터"
          - href: 43_geospatial.qmd          
            text: "공간정보 데이터"
          - href: 44_text_mining.qmd          
            text: "텍스트 데이터"            
          - text: "-----"
          - href: 51_nlp.qmd          
            text: "딥러닝 - NLP"
          - href: 52_vision.qmd
            text: "딥러닝 - 비젼"
      - text: "프로젝트"
        menu:
          - text: "-----"
          - href: project.qmd
            text: "프로젝트"
          - text: "-----"
          - href: py_tree.qmd
            text: "나무모형"
      - text: "데이터셋"
        menu:
          - href: data.qmd
            text: "데이터셋"
          - href: data_chatGPT.qmd
            text: "chatGPT 데이터셋"
      - text: "운동장"
        menu:
          - href: dataxray.qmd
            text: "데이터 X-레이"        
          - href: flexdashboard/penguin_flexdashboard.html
            text: "대쉬보드: 파머펭귄"
      - text: "퀴즈"
        menu:
          - href: mcq_stat.qmd
            text: "확률과 통계"
          - href: mcq_ds.qmd
            text: "데이터 과학"
          - href: mcq_ml.qmd
            text: "기계학습"            
          
format:
  html:
    theme: cosmo
      - litera
      - css/quarto-fonts.css
    toc: true

execute:
  freeze: true
  message: false
  warning: false


