---
title:      "파머 펭귄"
date:       "분석시간: `r format(Sys.time(),format='%A %d %b %Y  %I:%M %p %Z')`"
output: 
   flexdashboard::flex_dashboard: 
     self_contained: false
     mathjax: NULL
     source_code: embed 
editor_options: 
  chunk_output_type: console
---


```{r knitr-defaults}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = NA)
knitr::opts_chunk$set(cache = FALSE)
options(width=170)
```

```{r load-packages}
library(dataxray)
library(tidyverse)
library(haven)
library(crosstalk)
```

```{r sample-vars, include=FALSE}
data <- bitData::penguins

dim  <- dim(data)
data_xray <- make_xray(data)
```

# 데이터 X-레이 {#main}

Inputs {.sidebar data-width=300}
-------------------------------------

```{r} 
d_reactable <- data_xray   

d_reactable_shared <- SharedData$new(d_reactable)

filter_select('type', 'variable TYPE',    d_reactable_shared, ~ TYPE)
filter_select('var',  'variable NAME',    d_reactable_shared, ~ VAR)
filter_select('lab',  'variable LABEL',   d_reactable_shared, ~ LABEL)
filter_select('n',    'variable COMPLETE',d_reactable_shared, ~ ifelse(n == dim[1], 'YES', 'NO'))

filter_slider('missing', 'variable % MISSING', d_reactable_shared,  ~ 100*(missing/dim[1]),
              width = 250,
              post = '%',
              min = 0, max = 100,
              dragRange = FALSE,
              step = 5, round = TRUE, sep = '', ticks = TRUE)

filter_slider('distinct', 'variable # DISTINCT', d_reactable_shared, ~ distinct,
              width = 250,
              min = 1, dragRange = FALSE,
              step = 5, ticks = FALSE)
```

Column
-------------------------------------
###   파머 펭귄 데이터셋: **`r dim[1]`** 관측점과 **`r dim[2]`** 변수

```{r create-reactable-1}
view_xray(data_xray = d_reactable, data_xray_shared = d_reactable_shared)
```